name: Shared VHDL CI

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

      step:
        required: false
        type: string
        default: "setup build run"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/asylum-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # Enregistrement de la librairie locale pour FuseSoC
      - name: FuseSoC library
        run: |
          cd "$GITHUB_WORKSPACE"
          fusesoc library add https://github.com/deuskane/asylum-cores --global

      - name: Execute
        shell: bash
        run: |
          set -o pipefail
          make ${{ inputs.name }} STEP="${{ inputs.step }}"

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            log

#      # Extraction des métriques UVVM & Couverture
#      - name: Parsing des résultats
#        if: always()
#        run: |
#          PASSED=$(grep -c "UVVM: Summary: .* 0 NO REASON" simulation.log || grep -c "PASSED" simulation.log || true)
#          TOTAL=$(grep -c "UVVM: Summary:" simulation.log || grep -cE "PASSED|FAILED" simulation.log || true)
#          [ "$TOTAL" -eq "0" ] && PASSED=1 && TOTAL=1
#          echo "TESTS_SCORE=${PASSED}/${TOTAL} passed" >> $GITHUB_ENV
#
#          COVERAGE=$(gcovr --root . --json-summary | python3 -c "import sys, json; print(json.load(sys.stdin)['line_percent'])")
#          echo "COVERAGE_SCORE=${COVERAGE}%" >> $GITHUB_ENV
#
#      - name: Badge Coverage
#        if: always()
#        uses: Schneegans/dynamic-badges-action@v1.7.0
#        with:
#          auth: ${{ secrets.GIST_SECRET }}
#          gistID: TON_GIST_ID
#          filename: coverage.json
#          label: Coverage
#          message: ${{ env.COVERAGE_SCORE }}
#          valColorRange: ${{ env.COVERAGE_SCORE }}
#          minColorRange: 50
#          maxColorRange: 90
#
#      - name: Badge Tests (UVVM)
#        if: always()
#        uses: Schneegans/dynamic-badges-action@v1.7.0
#        with:
#          auth: ${{ secrets.GIST_SECRET }}
#          gistID: TON_GIST_ID
#          filename: tests.json
#          label: UVVM Tests
#          message: ${{ env.TESTS_SCORE }}
#          color: green
